name: doa_device_binding_api
version: 1.0.0
description: Generated dio client for the azuma doa Device Binding API v1.
homepage: homepage


environment:
  sdk: '^3.8.0'

dependencies:
  dio: '^5.11.0'
  json_annotation: '^4.12.0'

dev_dependencies:
  build_runner: any
  json_serializable: '^6.9.3'
  test: '^1.16.0'
